import type { Metadata } from 'next';
import { Plus_Jakarta_Sans } from 'next/font/google';
import './globals.css';
import Header from '@/components/header';

const plus_jakarta_sans = Plus_Jakarta_Sans({
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap'
});
// const dancing_script = Dancing_Script({
//   style: ['normal'],
//   subsets: ['latin'],
//   display: 'swap'
//   // variable: '--font-plus-jakarta-sans'
// });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${plus_jakarta_sans.className} bg-neutral-50`}>
        <div className="flex h-screen w-full flex-col">
          <div className="z-30">
            <Header />
          </div>
          <div className="flex-1 overflow-y-auto">{children}</div>
        </div>
      </body>
    </html>
  );
}
